### ISSUE TITLE
Unable to deploy a chart with an included library chart

### ISSUE THREAD

**Issue by onedr0p** [fluxcd/helm-controller#141] opened 2020-11-12 13:00 UTC
Hello!

I am on version 0.2.4 of flux2 and am having issues deploying a chart. We're working on creating a [library chart](https://helm.sh/docs/topics/library_charts/) for some of the charts we host. [This chart](https://github.com/k8s-at-home/charts/tree/master/charts/jackett) has a [common library chart](https://github.com/k8s-at-home/charts/tree/master/charts/common).

# How to replicate

## Apply the HelmRepository

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: k8s-at-home-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://k8s-at-home.com/charts/
  timeout: 3m
```

## Apply the HelmRelease

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m  
  values:
    controllerType: deployment
```

## Errors in logs

```
helmrelease.helm.toolkit.fluxcd.io/jackett                  False   Helm install failed: template: jackett/templates/common.yaml:1:3: executing "jackett/templates/common.yaml" at <include "common.all" .>: error calling include: template: jackett/charts/common/templates/_all.tpl:8:16: executing "common.all" at <.Values.addons.vpn.enabled>: nil pointer evaluating interface {}.vpn   12m
```

```
helmrelease.helm.toolkit.fluxcd.io/jackett                  False   Helm install failed: template: jackett/templates/common.yaml:1:3: executing "jackett/templates/common.yaml" at <include "common.all" .>: error calling include: template: jackett/charts/common/templates/_all.tpl:21:5: executing "common.all" at <include "common.service" .>: error calling include: template: jackett/charts/common/templates/_service.tpl:3:8: executing "common.service" at <include "common.classes.service" .>: error calling include: template: jackett/charts/common/templates/classes/_service.tpl:23:14: executing "common.classes.service" at <eq $svcType "ClusterIP">: error calling eq: incompatible types for comparison
```

## Debugging

I am able to run `helm template` over this and it generated the manifests correctly

```yaml
# values.yaml
---
controllerType: deployment
```

```
helm template \
    https://github.com/k8s-at-home/charts/releases/download/jackett-5.2.0/jackett-5.2.0.tgz \
    --values=./values.yaml \
    --output-dir=./ \
    --name-template=jackett \
    --version=5.2.0 \
    --namespace media
```

I have also noticed this helm chart works fine in Flux v1.

I have also made a post in slack if that's easier to help debugging.
https://cloud-native.slack.com/archives/CLAJ40HV3/p1605148705143800

Thanks again for all your amazing work on this tool!

**Comment by bjw-s** [comment] 2020-11-12 15:39
Some additional testing seems to have it pinpointed to the use of [`sprig`'s `merge`](https://github.com/Masterminds/sprig/blob/master/docs/dicts.md#merge-mustmerge) function within the library chart that is used by the mentioned Jackett chart. While trying to isolate the issue, i noticed the following:

Given the following simple configmap template:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  # WORKS
  userValues: |-
    {{- $userValues := omit .Values "common" -}}
    {{- $userValues | toYaml | nindent 4 }}

  # WORKS
  defaultValues: |-
    {{- $defaultValues := get .Values "common" -}}
    {{- $defaultValues | toYaml | nindent 4 }}

  # ?EMPTY STRING?:
  mergedValues: |-
    {{- $mergedValues := merge $userValues $defaultValues -}}
    {{- $mergedValues | toYaml | nindent 4 }}
```

Renders the following output in flux v2 (notice how `mergedValues` is an empty string):
```yaml
apiVersion: v1
data:
  defaultValues: |-
    service:
      additionalPorts: []
      additionalServices: []
      annotations: {}
      enabled: true
      labels: {}
      port:
        name: http
        port: ""
        protocol: TCP
        targetPort: http
      type: ClusterIP
    strategy:
      type: RollingUpdate
  mergedValues: ""
  userValues: |-
    service:
      port:
        port: 9117
    strategy:
      type: Recreate
```

When running `helm template` or `helm install` (and also in flux v1) this output is rendered as expected (notice how `mergedValues` is filled):
```yaml
apiVersion: v1
data:
  defaultValues: |-
    service:
      additionalPorts: []
      additionalServices: []
      annotations: {}
      enabled: true
      labels: {}
      port:
        name: http
        port: ""
        protocol: TCP
        targetPort: http
      type: ClusterIP
    strategy:
      type: RollingUpdate
  userValues: |-
    service:
      port:
        port: 9117
    strategy:
      type: Recreate
  mergedValues: |-
    service:
      additionalPorts: []
      additionalServices: []
      annotations: {}
      enabled: true
      labels: {}
      port:
        name: http
        port: 9117
        protocol: TCP
        targetPort: http
      type: ClusterIP
    strategy:
      type: Recreate
kind: ConfigMap
```

**Comment by bjw-s** [comment] 2020-11-12 18:41
Seems to be that the type validation in Flux v2 is somehow stricter than before (and in `helm template`). There was a value set as string in one of the values.yaml, whereas the value override in the chart was an int. That caused the following error:

{"level":"debug","ts":"2020-11-12T16:03:46.534Z","logger":"controller-runtime.manager.events","msg":"Normal","object":{"kind":"HelmRelease","namespace":"test","name":"test","uid":"df207251-c73f-4d61-befb-7d596cdb0ed3","apiVersion":"helm.toolkit.fluxcd.io/v2beta1","resourceVersion":"138550"},"reason":"error","message":"Helm install failed: template: test/templates/configmap.yaml:19:25: executing \"test/templates/configmap.yaml\" at <mustMerge $userValues $defaultValues>: error calling mustMerge: cannot append two different types (string, float64)"}

**Closed** 2020-11-13 20:13 UTC

**Comment by onedr0p** [comment] 2020-11-13 20:14
This was an issue with our chart that we corrected, but flux2 is the only one that has an issue.

I'll close the issue unless other people report in having a similar issue.

**Comment by seaneagan** [comment] 2020-12-03 22:24
Likely the same root cause as #152
