### ISSUE TITLE
High Memory Usage after helm-controller v0.12.0 upgrade

### ISSUE THREAD

**Issue by Legion2** [fluxcd/helm-controller#345] opened 2021-10-24 16:41 UTC
I updated to helm-controller v0.12.1 and started using `ReconcileStrategy` `Revision` for all my local helm charts. Now helm-controller is restarted each time I push a commit to the GitRepository source, because helm-controller uses too much memory and is killed by kubernetes (OOMKilled). As a result of the controller being killed by kubernetes, some helm release are stuck in the upgrade process which must be manually rolled back (https://github.com/helm/helm/issues/8987).
![image](https://user-images.githubusercontent.com/12752323/138603834-201d4897-cb9e-474a-bf32-5fdc3010781d.png)

**Comment by tehlers320** [comment] 2021-11-02 15:53
I'm not sure this is just the revision strategy. We do not use this anywhere and have seen a huge jump in memory use.  I grabbed a pprof heap map. 
![out](https://user-images.githubusercontent.com/16598119/139885982-3255e200-c952-4db5-aa8e-8e3d74052339.png)

**Comment by hiddeco** [comment] 2021-11-02 16:08
@tehlers320 can you provide more information about the version you upgraded from?

**Comment by tehlers320** [comment] 2021-11-02 16:17
@hiddeco we jumped from 0.10.2 and do not use the new reconcile revision.  Its been running for 5 days (when it can, OOMkiller). Sorry i don't mean to walk over this issue, but i think perhaps its not related to the reconcilestrategy since we dont use Revision. 

Should i make a new one or do you think the issue is both?

**Comment by hiddeco** [comment] 2021-11-02 16:41
No, I think your observations are correct based on other reports on Slack.

Did a quick dive into it with the limited time I had available, but the helm-controller didn't really change much besides Helm, kustomize and controller-runtime updates. It would be useful if someone could pinpoint the resource behavior change to an exact helm-controller version, which would help identifying the issue.

I am at present working on Helm improvement changes for the source-controller in the area of Helm repository index, dependency, and chart build memory consumption. Once that's done, I have time (and am planning) to look in much greater detail at the current shape of the helm-controller (as part of https://github.com/fluxcd/helm-controller/milestone/1).

**Comment by glen-uc** [comment] 2021-11-03 11:47
We are facing the same issue where the memory of helm controller keeps on growing

We upgraded from 0.16.2 (no issue with helm controller in this version) > 0.19.1 (started seeing issues ) > 0.20.1

We have around 258 helm releases and 8 helm repo's in our cluster with the interval set to 24h 

We have set 4GB as the memory limit for our helm controller

Here is the output of `curl -Sk -v http://<helm_controller>:8080/debug/pprof/heap

![profile001](https://user-images.githubusercontent.com/41667680/140054419-e3b61164-7948-4f2c-9f83-278ade7d9d92.png)
bug/pprof/heap` 

[heap.zip](https://github.com/fluxcd/helm-controller/files/7467288/heap.zip)

**Comment by stefanprodan** [comment] 2021-11-03 13:40
I've spend the day digging around to find the root cause of the sudden increate in memory usage. Here is what I've found:
- in this [commit](https://github.com/kubernetes/kubectl/commit/579299d5e24544cf1cb6a040701c1d21a57fdbb7) kubectl switched to `k8s.io/kube-openapi` (released in Kubernetes v0.22)
- helm v3.7.0 comes with the kubectl package that uses `k8s.io/kube-openapi`
- the `k8s.io/kube-openapi` has bug where it consumes large amounts of memory https://github.com/kubernetes/kubernetes/issues/101755
- there is a fix underway https://github.com/kubernetes/kube-openapi/pull/251

We can't do much in Flux, we have to wait for that PR to get merged, then wait for a Kubernetes release, then wait for a Helm release that uses the latest Kubernetes release and finally update Helm in Flux to stop the OOM issues.

I propose we revert Helm to v3.6.3 for a couple of months until the `kube-openapi` fixes end up in Helm.

**Comment by glen-uc** [comment] 2021-11-04 11:35
We have been using helm controller with `ghcr.io/fluxcd/helm-controller:rc-4fe7a7c8` image for a couple of hours and already seeing a large reduction in memory footprint when compared to `ghcr.io/fluxcd/helm-controller:v0.12.1`

After a couple of hours in our staging cluster, `ghcr.io/fluxcd/helm-controller:v0.12.1` used to consume around 4GB+ and crash as we have set the limit as 4GB, `ghcr.io/fluxcd/helm-controller:rc-4fe7a7c8`  is barely using 200MB

We will monitor the controller for few more days

**Comment by stefanprodan** [comment] 2021-11-04 12:08
@glen-uc could you help test another variant? I would like to see if we could keep Helm at the latest version and only replace `kube-openapi` with `go-openapi`.

**Comment by glen-uc** [comment] 2021-11-04 13:34
@stefanprodan Sure, if you give the image I can test it out in our staging cluster

**Comment by stefanprodan** [comment] 2021-11-04 14:06
Please give `ghcr.io/fluxcd/helm-controller:rc-725fd784` a spin, this is built from #354 

Thank you!

**Comment by glen-uc** [comment] 2021-11-04 14:20
@stefanprodan I have deployed hem controller with the image provided, will monitor it for a couple of hours and look for restarts due to OOM Kill

```
flux: v0.21.0
helm-controller: rc-725fd784
image-automation-controller: v0.16.0
image-reflector-controller: v0.13.0
kustomize-controller: v0.16.0
notification-controller: v0.18.1
source-controller: v0.17.1

```

**Comment by glen-uc** [comment] 2021-11-05 11:31
@stefanprodan I'm glad I could help

Our staging cluster is using helm controller with  `ghcr.io/fluxcd/helm-controller:rc-725fd784` for a couple of hours now

Memory footprint is very minimal (< 100 MB) and we haven't observed any restarts due to OOM Kill

We will monitor the controller for few more days

```
flux: v0.21.0
helm-controller: rc-725fd784
image-automation-controller: v0.16.0
image-reflector-controller: v0.13.0
kustomize-controller: v0.16.0
notification-controller: v0.18.1
source-controller: v0.17.1
```

**Comment by hiddeco** [comment] 2021-11-05 11:33
Awesome, and thanks a lot for helping out. This seems to indicate that we can at least temporary work around the upstream problems by forcing the replacement of that specific Helm dependency, without having to stop receiving new Helm updates.

**Comment by Legion2** [comment] 2021-11-07 13:24
I also tested `ghcr.io/fluxcd/helm-controller:rc-725fd784` and experienced an OOM after 2 days at 2GiB usage. It looks like the momory usage of `ghcr.io/fluxcd/helm-controller:rc-725fd784` is similar to the current release version.

**Comment by hiddeco** [comment] 2021-11-07 18:30
@Legion2 would you be able to grab a pprof profile, as done for the graph in one of the comments above?

You can send it to me via DM on CNCF Slack (`@hidde`) or mail (`hidde <at> weave.works`).

**Comment by hiddeco** [comment] 2021-11-08 09:23
Received a HEAP profile from @Legion2 which generates the following map:

![HEAP profile](https://user-images.githubusercontent.com/10063039/140716283-3f5eaa30-5432-4423-89a7-5e8f686267e5.png)

What version was this for Leon? This information was not included in your mail.

**Comment by stefanprodan** [comment] 2021-11-08 09:47
@Legion2 can you please run `flux version` against the cluster where the above profile was taken and post it here?

**Comment by stefanprodan** [comment] 2021-11-08 09:53
@Legion2 can you please try `rc-4fe7a7c8`?

**Comment by Legion2** [comment] 2021-11-08 09:56
> @Legion2 can you please try `rc-4fe7a7c8`?

yes

**Comment by glen-uc** [comment] 2021-11-11 04:46
There is an update from my end, like @Legion2 with helm `rc-725fd784` i started seeing restarts due to OOM Kill after 1 day (with memory limit set to 1GB) hence I promptly reverted the helm controller to `rc-4fe7a7c8` it has been running for 3 days without any restarts

Unfortunately, I don't have the memory profile of the helm controller when it was running on `rc-725fd784`

I Will monitor `rc-4fe7a7c` for a few more days 


```
flux: v0.21.0
helm-controller: rc-4fe7a7c8
image-automation-controller: v0.16.0
image-reflector-controller: v0.13.0
kustomize-controller: v0.16.0
notification-controller: v0.18.1
source-controller: v0.17.1
```

**Comment by hiddeco** [comment] 2021-11-11 11:39
@stefanprodan I think we should deem `rc-4fe7a7c8` the successor for now.

**Comment by hiddeco** [comment] 2021-11-11 14:12
Thanks all for testing. This should now also be solved by updating the helm-controller Deployment image to `v0.12.2`. 

CLI release for `flux bootstrap`, etc. will arrive later today.

**Comment by poblish** [comment] 2021-11-12 10:58
We're seeing a 75% drop in `helm-controller` memory (peaks and base level) since picking this up version 👍

**Comment by hiddeco** [comment] 2021-12-09 13:40
Helm released a patch yesterday which likely addresses this issue

Due to the holiday period that is arriving pretty soon however, I am hesitant in releasing this as I will be on leave for 3 weeks. Unless someone has specific needs for the v3.7.x release range, in which case I can provide a RC.

**Comment by hiddeco** [comment] 2021-12-10 09:53
Based on the PR above, a RC with Helm 3.7.2 is available as `docker.io/fluxcd/helm-controller:rc-helm-3.7.2--a12eae8e`

**Comment by stefanprodan** [comment] 2022-01-07 16:04
We are going ahead with the Helm v3.7.2 as v3.6.3 blocks us from fixing the containerd CVEs due to ORAS breaking changes. In case v3.7.2 brings back the memory leak please pin helm-controller to `v0.12.2`.

**Comment by Legion2** [comment] 2022-01-18 18:12
I updated flux to the latest version and can confirm that the memory leak is still present, will pin helm-controller to v0.12.2.

**Comment by poblish** [comment] 2022-02-04 12:37
Is it still sensible for us to try to pin the helm-controller version to avoid this? We're still using Flux v0.24.1 / helm-controller v0.14.1, but don't want to get too far behind, now that 0.26.x is released.

**Comment by hiddeco** [comment] 2022-02-04 12:57
This issue has been confirmed to be solved in the latest release (https://github.com/fluxcd/helm-controller/releases/tag/v0.16.0) via https://github.com/fluxcd/helm-controller/pull/409.

**Closed by hiddeco** 2022-02-04 12:57 UTC
Labels: bug, area/helm
