### ISSUE TITLE
Support insecure OCI chart sources

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/helm-controller#782] opened 2023-10-01 03:13 UTC
I know that we were waiting for support to land in Helm upstream, and it was going to take a next minor release for that to be available. Now Helm 3.13.0 is out, as of 3 days ago.

I believe this is the PR we were waiting for:

* https://github.com/helm/helm/pull/12128

Are there any other supportive changes required, or is it possible to add the support for `insecure` in HelmRepository with type oci? This came up in a conversation with an end-user, and I wanted to be sure we have a tracking issue for this now.

**Comment by stefanprodan** [comment] 2023-10-01 08:57
Duplicate of: https://github.com/fluxcd/source-controller/issues/957

**Closed** 2023-11-23 08:18 UTC
