### ISSUE TITLE
scheme "oci" not supported

### ISSUE THREAD

**Issue by tibberg** [fluxcd/helm-controller#224] opened 2021-02-24 07:59 UTC
I wanted to use AWS ECR as a helm repository (see https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html). 
I pushed my chart there. Then I wanted to specify this as a subchart with the `oci://` schema (see https://helm.sh/docs/topics/registries/#specifying-dependencies). 
I even tried to add the `HELM_EXPERIMENTAL_OCI=1` as `env` for the helm controller with no help. 
All I got was the error message saying `scheme "oci" not supported`

**Comment by hiddeco** [comment] 2021-02-24 08:29
Duplicate of https://github.com/fluxcd/source-controller/issues/124

**Closed by hiddeco** 2021-02-24 08:29 UTC
