### ISSUE TITLE
HelmRepository type oci is not having status object

### ISSUE THREAD

**Issue by sebastiangaiser** [fluxcd/helm-controller#866] opened 2024-01-09 10:29 UTC
Hey,

we implemented the [Flux custom Prometheus metrics](https://fluxcd.io/flux/monitoring/custom-metrics/) and discovered that the status object of HelmRepository with type oci is empty which should be exported as [described here](https://github.com/fluxcd/flux2-monitoring-example/blob/5274d23c2ba3779c75a0ead739a127a91055455a/monitoring/controllers/kube-prometheus-stack/kube-state-metrics-config.yaml#L129).

Steps to reproduce:
```
kubectl apply -f - <<EOF
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/stefanprodan/charts
EOF
```
```
flux get sources helm podinfo
NAME    REVISION        SUSPENDED       READY   MESSAGE                  
podinfo                 False           True    Helm repository is Ready
```
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1beta2","kind":"HelmRepository","metadata":{"annotations":{},"name":"podinfo","namespace":"flux-system"},"spec":{"interval":"5m0s","type":"oci","url":"oci://ghcr.io/stefanprodan/charts"}}
  creationTimestamp: "2024-01-09T10:14:40Z"
  generation: 1
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  provider: generic
  type: oci
  url: oci://ghcr.io/stefanprodan/charts
status: {}
```

helm-controller: `Image: ghcr.io/fluxcd/helm-controller:v0.37.2`

For "normal" HelmRepositories this is working fine.

**Comment by hiddeco** [comment] 2024-01-09 10:42
Duplicate of https://github.com/fluxcd/flux2/issues/4469

**Closed by hiddeco** 2024-01-09 10:42 UTC

**Comment by sebastiangaiser** [comment] 2024-01-09 10:46
Thanks for your answer @hiddeco 
I would be interested in how to monitor such objects. Can you please point me to some docs.

**Comment by stefanprodan** [comment] 2024-01-09 11:39
You would not monitor the HelmRepository but the HelmChart, there is no way for Flux validate the OCI `HelmRepository.spec.url` without a chart as the URL is just a prefix.

**Comment by sebastiangaiser** [comment] 2024-01-09 13:43
For me this feels a bit weird to deploy a invalid `HelmRepository`, flux cli shows me `Helm repository is Ready` but no chart is showing up when running `flux get sources chart` because then I can't monitor a chart that is not existing.

**Comment by kingdonb** [comment] 2024-01-15 13:31
The HelmRepository is "actuated" by a HelmRelease. It is a bit weird, but the status change is aligned with Helm upstream which drops actions like `helm repo add` and `helm repo update` from the workflow when using OCI helm repositories. This is a difference in the user experience of OCI vs. legacy Helm repositories, it's aligned with Helm upstream, and we thought to mention it at the Flux maintainer talk in Detroit, but avoided the topic because it's a decision for Helm upstream to make.

We (Flux devs) should not be the ones responsible for telling Helm users how to hold Helm or how to interpret changes from Helm upstream. But there might need to be some extension to the docs to clarify this issue, since it is a usability change.

In the Helm SDK, until you have a version spec to check the tag list against, there is no bit of code which looks at tags and so there is no way for Helm to test the HelmRepository without the `spec.chart` from the HelmRelease which actuates it.

We therefore don't have any action which is taken when `flux reconcile source helm` hits a `HelmRepository` of `type: oci`.

It is a tough choice for the user interface experience and a decision had to be made over whether to show a Ready status or show an empty status block that users will likely interpret as something wrong with the controller.

But from a kstatus perspective, I think it's an easy choice, and I think it has been implemented correctly: the OCI helmrepo needs to conform and look Ready for kstatus, else there are likely things which may block on the not-ready looking status.

**Comment by sebastiangaiser** [comment] 2024-01-15 14:19
Thank you for your detailed explanation. 

> It is a tough choice for the user interface experience and a decision had to be made over whether to show a Ready status or show an empty status block that some users will likely interpret as something wrong with the controller.

I think this depends. Showing a Ready status if it is not checked (which is not possible as you wrote) might not be the "best one". For me, just showing that the resources got reconciled and showing a revision would fit better.

**Comment by kingdonb** [comment] 2024-01-15 15:49
Understanding that in the latest Helm Controller/Source Controller there is no function which reconciles the helmrepo at all (since there is no index.yaml to fetch at all) is the point of this contention;

Ideally the users don't need to know all this, but instead the UI can pass through status artifacts and intuitively gauge when the user is trying to check to facilitate a pass through status check. This is sorta how we handled it for the vscode GitOps Tools extension, the "reconcile with source" function calls through and waits for the chart before reconciling the dependent HelmRelease. The CLI doesn't go as far.
